feat: #11 - Add an advanced game in C
OWASP/wrongsecrets-binaries pull request #29
Opened 2023-06-22 01:39 UTC by roddas

This PR adds a password guess game in C, in which the key is encoded in hexadecimal format.

(I hope it fits your needs).

2023-06-22 05:19 UTC, commjoen commented
Hi @roddas this looks like fun! Can you implement the “spoil” function and such as well please as we have with the other binaries ? This allows it to be usable with WrongSecrets challenges ;-)

2023-06-22 11:06 UTC, roddas commented
Yes, I'll do it. I didn't know that this function was mandatory.

Sorry about that.

2023-06-22 18:14 UTC, roddas commented
@commjoen you can take a look when you're available. I made the changes you required.

2023-06-22 18:40 UTC, commjoen commented
Hi @roddas , will take a look in a week or so :-)

2023-06-24 03:51 UTC, commjoen requested changes
Hi @roddas ! Thank you for submitting a PR to wrongsecrets Binaries. I like its initial direction Can you please have a look at the comments? 
And can you please extend quickbuild.sh to implement the other task of https://github.com/OWASP/wrongsecrets-binaries/issues/11 ?

Last but not least, in https://github.com/OWASP/wrongsecrets-binaries/issues/11 we wanted to encrypt the secret data entries with a hardcoded key, using something like https://github.com/kokke/tiny-AES-C can you add that as well please?

2023-06-24 03:51 UTC, commjoen commented on c/hex_challenge.c
> +	printf("This is a hardcoded secret game in C\n");
spoiling should return the actual secret of the challenge

2023-06-24 03:51 UTC, commjoen commented on c/hex_challenge.c
> +		printf("root:~# You're root :-D\n");
Please have a look at https://github.com/OWASP/wrongsecrets-binaries/blob/main/c/main.c : there are "standard" return values that wrongsecrets can pick up right now. Best would be if succesful solutions still print out the same `This is correct! Congrats!\n`
```suggestion
		printf("This is correct! Congrats!\n");
```

2023-06-24 03:51 UTC, commjoen commented on c/hex_challenge.c
> +		puts("Try again");
```suggestion
		puts(""This is incorrect. Try again\n");
```
Standardized error messages will be read by WrongSecrets to decide on whether it works or not.

2023-06-24 03:51 UTC, commjoen commented on c/hex_challenge.c
> +		puts("You're almost there champion! Here's two hints: ");
```suggestion
		puts("This is incorrect. Try again\n")
		puts("You're almost there champion! Here's two hints: ");
```

2023-06-24 07:02 UTC, commjoen commented
Apologies for never giving the repository the guiding docs for all the feedback given now. Because of your awesome work, I started documenting them at https://github.com/OWASP/wrongsecrets-binaries/pull/30

2023-06-27 00:27 UTC, roddas commented
That's okay @commjoen, I'll make the proper corrections and I appreciate it very much.

2023-06-28 13:52 UTC, roddas commented
@commjoen you can now take a look. I made the requested changes.

2023-06-29 04:23 UTC, commjoen commented
Can you extend https://github.com/OWASP/wrongsecrets-binaries/blob/main/quickbuild.sh with the automated steps for building the binary, please? then we can test it locally ;)

2023-06-29 10:10 UTC, roddas commented
Sure.

2023-07-01 05:21 UTC, commjoen commented
Thank you @roddas ! Will have a look next week at this :)

2023-07-02 05:44 UTC, commjoen commented on c/advanced/advanced.c
> +    return "This is a hardcoded secret in C";
This is unfortunately not the real answer. Can you make spoil return the actual answer, please? This can often be done by storing a double encrypted value of your secret that you decrypt when spoil is called.

2023-07-04 11:59 UTC, roddas commented on c/advanced/advanced.c
> +    return "This is a hardcoded secret in C";
I got It. thanks . I'll do it .

2023-07-17 22:54 UTC, roddas commented on c/advanced/advanced.c
> +    return "This is a hardcoded secret in C";
@commjoen  I updated the message.

2023-08-12 05:48 UTC, commjoen approved these changes
This is a really fun challenge that works nicely different from the hardcoded string fun we currently have in C. thank you @roddas !

2023-08-12 14:39 UTC, bendehaan approved these changes
Awesome contribution, thanks a lot!

2023-08-12 15:11 UTC, roddas commented
Thanks to you, especially to you @commjoen  who guided me in the right way and had a lot of patience with me.

2023-08-12 19:40 UTC, merged