add makefiles for c/c++ with cppcheck
OWASP/wrongsecrets-binaries pull request #40
Opened 2023-10-01 12:12 UTC by diamant3

### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [x] Something else

#### Description
add makefiles for each c/c++ dir with cppcheck according to #16

### Relations

Closes #16

### References

### Checklist:

-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] Quickbuild.sh is extended to compile the binary for all target environnments
-   [ ] Github actions are implemented to publish the new challenge
-   [ ] A spoil command is implemented to return the actual answer
-   [ ] The correct and incorrect answer strings are compliant with Contributing.md.
-   [ ] The PR passes pre-commit hooks and automated tests

2023-10-01 18:32 UTC, commjoen requested changes
Hi @diamant3 !
Thank you for your PR!
Love this! Only some minor feedback :) Can you please have a look and apply the fixes, so we can get you that `hacktoberfest-approved` label :) ?

2023-10-01 18:32 UTC, commjoen commented on c/Makefile
> +	$(CPPCHECK) $(SRC)
Can you please:
-  add a print out to the check on where to obtain cppcheck for folks that want to use this? 
- update the https://github.com/OWASP/wrongsecrets-binaries/blob/main/quickbuild.sh to include calling this make file instead :) ?

2023-10-01 18:32 UTC, commjoen commented on c/advanced/Makefile
> +check:
Can you please:
-  add a print out to the check on where to obtain cppcheck for folks that want to use this? 
- update the https://github.com/OWASP/wrongsecrets-binaries/blob/main/quickbuild.sh to include calling this make file instead :) ?

2023-10-01 18:32 UTC, commjoen commented on cplus/Makefile
> +check:
Can you please:
-  add a print out to the check on where to obtain cppcheck for folks that want to use this? 
- update the https://github.com/OWASP/wrongsecrets-binaries/blob/main/quickbuild.sh to include calling this make file instead :) ?

2023-10-02 03:59 UTC, diamant3 commented
Thank you for the feedback!. Got it, let me work on that later

2023-10-02 07:04 UTC, diamant3 commented
Hello, about the dockercross, do I need to update too?

2023-10-02 07:33 UTC, commjoen commented
No sir, no need for that, thank you! Can you replace https://github.com/OWASP/wrongsecrets-binaries/blob/main/.github/workflows/compile_c.yml#L24 with your make file call instead ;) ? then we are 🏁

2023-10-02 07:35 UTC, commjoen commented
I am also fine if you do that in a separate pr btw, let's roudn this one off ;)

2023-10-02 07:36 UTC, commjoen commented
Can you for now, please delete `c/advanced/advanced` on your end and commit the deletion? then we should be good to go. feel free to file another PR with the github action being updated for another hacktoberfest point :-D

2023-10-02 07:55 UTC, diamant3 commented
Really? Thanks! Okay let me delete that

2023-10-02 08:00 UTC, diamant3 commented
Sorry, I forgot to remove that, anyway thank you so much for accepting my PR!

2023-10-02 08:00 UTC, commjoen approved these changes
Thank you so much! One more issue down :) .

2023-10-02 08:01 UTC, merged

2023-10-02 08:02 UTC, commjoen commented
@diamant3 : can you please let me know your name with which you want to be listed as a contributor?

2023-10-02 08:04 UTC, diamant3 commented
`diamant3` is fine to me, thank you!

2023-10-02 08:06 UTC, commjoen commented
Awesome Diamond  ! will add it soon :) . Can you file the other PR to fix the integration please :) ?

2023-10-02 08:08 UTC, diamant3 commented
Got it! Okay I will work on that!